version: '3'

services:
  mysql:
    image: 'lizhongwei/mysql:latest'
    container_name: mysql
    ports:
      - 13306:3306
    #volumes:
    #  - ./init/mysql/:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_DATABASE=admin
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=123456
      - MYSQL_RANDOM_ROOT_PASSWORD="yes"
      - TZ=Asia/Shanghai
    command:
      # MySQL8的密码验证方式默认是 caching_sha2_password，但是很多的连接工具还不支持该方式
      # 就需要手动设置下mysql的密码认证方式为以前的 mysql_native_password 方式
      --default-authentication-plugin=mysql_native_password
      --max_connections=1000
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "--protocol=tcp"]
        timeout: 240s
        interval: 1s
        retries: 20

  goadmin:
    image: 'lizhongwei/goadmin:latest'
    ports:
      - 8000:8000
    environment:
      - POSTGRES_USER=gorm
      - POSTGRES_DB=gorm
      - POSTGRES_PASSWORD=gorm
    depends_on:
      mysql:
        condition: service_healthy
  vue-admin:
    image: 'lizhongwei/vue-admin:latest'
    ports: 
      - 80:80
